### ISSUE TITLE
Land sollte angegeben werden

### ISSUE THREAD

**Issue by DasFragezeichen** [unverantwortli-ch/list#10]
Es sollte ggf. das Land mit angegeben werden wo es den Vorfall gab.
Gerade beim letzten Eintrag "Bundesministerium für Soziales, Gesundheit, Pflege und Konsumentenschutz" sollte erwähnt werden, dass es um Österreich geht.

**Comment by heinleit** [comment]
Ja, ist vielleicht eine gute Idee.

**Comment by heinleit** [comment]
Vielleicht auch in der Hinsicht, dass zum Beispiel Microsoft US anders reagiert, als Microsoft DE.
